# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  jaymediaclient:
    image: jaymediaclient
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on:
      - jaymediaapi
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "start"]

  jaymediaapi:
    image: jaymediaapi
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5090:5090
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
    volumes:
      - ./backend:/app
      - ~/.vsdbg:c:\remote_debugger:rw
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:5090"]

  database:
    image: postgres:17
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Joyeseosa
      POSTGRES_DB: JayMediaDB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
